[package]
name = "mun_codegen"
version = "0.2.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2018"
description = "LLVM IR code generation for Mun"
documentation = "https://docs.mun-lang.org/v0.2"
readme = "README.md"
homepage = "https://mun-lang.org"
repository = "https://github.com/mun-lang/mun"
license = "MIT OR Apache-2.0"
keywords = ["game", "hot-reloading", "language", "mun", "scripting"]
categories = ["Game development", "Mun"]

[dependencies]
abi = { version = "=0.2.0", path = "../mun_abi", package = "mun_abi" }
hir = { version = "=0.2.0", path = "../mun_hir", package = "mun_hir" }
mun_target = { version = "=0.2.0", path = "../mun_target" }
mun_lld = { version = "=70.2.0", path = "../mun_lld" }
failure = "0.1.7"
salsa="0.14"
md5="0.6.1"
array-init="0.1.0"
tempfile = "3"
paste = "0.1.6"

[dependencies.inkwell]
git = "https://github.com/mun-lang/inkwell"
rev = "4448bcd"
features = ["llvm7-0"]

[dev-dependencies]
insta = "0.12.0"
parking_lot = "0.10"

[build-dependencies]
semver = "0.9.0"
regex = "1.3.1"
